### ISSUE TITLE
pydicom_PIL.py cant handle DICOM files that have multiple window width and center setting

### ISSUE THREAD

**Issue by scaramallion** [pydicom/contrib-pydicom#1]
Let's try this again...

#### Description
Some DICOM file may have multiple window width and center setting, like ["400","40"] ["400","400"]. And this will cause pydicom_PIL.get_PIL_image to throw "MultiValued cant minus Float" exception

[Original issue](https://github.com/pydicom/pydicom/issues/330) reported by @tenggyut

**Comment by liamnaka** [comment]
_Copied from the thread above at the request of @scaramallion_ 

Got it to work by placing this in the` get_LUT_value` method:

```python
if type(window) is MultiValue: 
       window = window[0] 
if type(level) is MultiValue: 
       level = level[0]
```

Make sure to also put `from dicom.multival import MultiValue` at the top of the file. If there are multiple window settings, this will use the first one given.
