### ISSUE TITLE
dicomtree.py example not working due to tix

### ISSUE THREAD

**Issue by massich** [pydicom/contrib-pydicom#2]
#### Description
This is a migration from [this pydicom issue](https://github.com/pydicom/pydicom/issues/379#issuecomment-313898776)

## Original Issue

I'm going through the examples and I can not run dicomtree. 

```sh
$ python dicomtree.py ~/Documents/my_dicomdir/

Traceback (most recent call last):
  File "dicomtree.py", line 71, in <module>
    root = tkinter_tix.Tk()
  File "/home/sik/miniconda3/lib/python3.6/tkinter/tix.py", lin
e 218, in __init__                                            
    self.tk.eval('package require Tix')
_tkinter.TclError: can't find package Tix
```
The main problem is `tix`, see the following ipython session:
```python
from tkinter import tix
from tkinter.constants import *
root = tix.Tk()
```
```sh
Traceback (most recent call last):
  File "<ipython-input-20-c03089e228b3>", line 3, in <module>
    root = tix.Tk()
  File "/home/sik/miniconda3/lib/python3.6/tkinter/tix.py", line 218, in __init__
    self.tk.eval('package require Tix')
TclError: can't find package Tix
```

I don't understand the error since the libraries seem to be at the right place according to [this thread](https://stackoverflow.com/questions/22780141/tkinter-tclerror-cant-find-package-tix)

```sh
$ ldconfig -p | grep Tix
	libTix8.4.3.so.1 (libc6,x86-64) => /usr/lib/libTix8.4.3.so.1
	libTix8.4.3.so (libc6,x86-64) => /usr/lib/libTix8.4.3.so
```
This is my configuration:
```
Linux-4.8.0-49-generic-x86_64-with-debian-stretch-sid
Python 3.6.0 |Continuum Analytics, Inc.| (default, Dec 23 2016, 12:22:00) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]
ttk 0.3.1
```

More over `tix` is deprecated  in fabour of ttk. ([see python doc](https://docs.python.org/3.6/library/tkinter.tix.html#using-tix))

**Comment by vsoch** [comment]
what output did this use to make? There are many lovely ways to show a file hierarchy, or image fields. If we want python (obviously) I would advocate for a simple flask (or other) script that just opens up a standard html/javascript view.

**Comment by vsoch** [comment]
Eg, this is just django: https://pydicom.github.io/dicom-database/interface.html

**Comment by ferdymercury** [comment]
Can you try this workaround?

```
try:
    if compat.in_py2:
        import Tix as tkinter_tix
    else:
        import tkinter.tix as tkinter_tix
except:
    import tkinter.tix as tkinter_tix
```

And did you do:
`sudo apt install tix-dev`
?

**Comment by darcymason** [comment]
Archiving contrib repository, closing issues first...
