### ISSUE TITLE
Fix slice spacing computation in `pydicom_series.py`

### ISSUE THREAD

**Issue by jond01** [pydicom/contrib-pydicom#22]
The calculated `distance_sum` takes care only of `ImagePositionPatient`:

https://github.com/pydicom/contrib-pydicom/blob/cbd27f1ac523863aeba820edf796bf040d63993f/input-output/pydicom_series.py#L662-L669

However, to compute the slice spacing one also has to take care of `ImageOrientationPatient`, see [dicom_numpy](https://github.com/innolitics/dicom-numpy/blob/204e95594a527bbab1444f9248432ffa01af024c/dicom_numpy/combine_slices.py#L250-L256)'s implementation.

**Comment by darcymason** [comment]
Archiving contrib repository, closing issues first...
