### ISSUE TITLE
Sort method can not be called from DicomSeries._ datasets

### ISSUE THREAD

**Issue by shinaji** [pydicom/contrib-pydicom#5]
#### Description
Since pydicom.multival.MultiValue now inherits MutableSequence, the sort method can not be called from DicomSeries._ datasets.

#### Contribution Folder or Script with Issue
input-output/pydicom_series.py

#### Steps/Code to Reproduce

```py
pydicom_series.read_files('{}/SE0/'.format(target_dir))
```
```
File "./contrib-pydicom/pydicom_series.py", line 580, in _sort
    self._datasets.sort(key=lambda k: k.InstanceNumber)
AttributeError: 'Sequence' object has no attribute 'sort'
```

#### Versions
python3.6

**Comment by mrbean-bremen** [comment]
@shinaji: I added a PR in the pydicom repo to add `sort` to `MultiValue` - this is more convenient than having to access the internal list.

**Comment by shinaji** [comment]
Thank you, mrbean-bremen !
